name: news-feedback-fetch
channels:
  - defaults
  - conda-forge
dependencies:
  - ca-certificates=2023.7.22
  - cudatoolkit=11.2.2
  - cudnn=8.1.0.77
  - openssl=3.0.9
  - pip=23.2.1
  - python=3.9.17
  - setuptools=68.0.0
  - sqlite=3.41.2
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.38.4
  - pip:
      - absl-py==1.4.0
      - astunparse==1.6.3
      - bcrypt==4.0.1
      - blinker==1.6.2
      - cachetools==5.3.1
      - certifi==2023.7.22
      - cffi==1.15.1
      - charset-normalizer==3.2.0
      - click==8.1.6
      - colorama==0.4.6
      - cryptography==41.0.3
      - filelock==3.12.2
      - flask==2.3.2
      - flask-cors==4.0.0
      - flatbuffers==23.5.26
      - fsspec==2023.6.0
      - gast==0.4.0
      - google-auth==2.22.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.56.2
      - h5py==3.9.0
      - huggingface-hub==0.16.4
      - idna==3.4
      - importlib-metadata==6.8.0
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - joblib==1.3.1
      - keras==2.10.0
      - keras-preprocessing==1.1.2
      - libclang==16.0.6
      - markdown==3.4.4
      - markupsafe==2.1.3
      - mpmath==1.3.0
      - networkx==3.1
      - nltk==3.8.1
      - numpy==1.25.2
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==23.1
      - pandas==2.0.3
      - paramiko==3.3.1
      - pillow==10.0.0
      - protobuf==3.19.6
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pynacl==1.5.0
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyyaml==6.0.1
      - regex==2023.6.3
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - safetensors==0.3.1
      - scikit-learn==1.2.2
      - scipy==1.11.1
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - six==1.16.0
      - sympy==1.12
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.10.0
      - tensorflow-estimator==2.10.0
      - tensorflow-hub==0.14.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.3.0
      - threadpoolctl==3.2.0
      - tokenizers==0.13.3
      - torch==2.0.1
      - torchvision==0.15.2
      - tqdm==4.65.0
      - transformers==4.31.0
      - typing-extensions==4.7.1
      - tzdata==2023.3
      - urllib3==1.26.16
      - werkzeug==2.3.6
      - wrapt==1.15.0
      - zipp==3.16.2